# Generated by Django 5.1.15 on 2026-09-10 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exploitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'exploitation")),
                ('localisation', models.CharField(blank=True, max_length=150, verbose_name='Localisation')),
                ('effectif_initial', models.PositiveIntegerField(default=0, verbose_name='Effectif initial (sujets)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exploitation',
                'verbose_name_plural': 'Exploitations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FicheVaccinationEauBoisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fiche', models.PositiveIntegerField(verbose_name='N° de la fiche')),
                ('date', models.DateField(verbose_name='Date')),
                ('age_sujets', models.CharField(max_length=50, verbose_name='Âge des sujets')),
                ('nombre_sujets', models.PositiveIntegerField(verbose_name='Nombre de sujets')),
                ('nombre_doses_utilise', models.PositiveIntegerField(verbose_name='Nombre de doses utilisées')),
                ('vaccin_utilise', models.CharField(max_length=150, verbose_name='Vaccin utilisé (nom)')),
                ('type_eau_utilisee', models.CharField(choices=[('PUITS', 'Puits'), ('FORAGE', 'Forage')], max_length=10, verbose_name="Type d'eau utilisée")),
                ('quantite_eau_initiale', models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Quantité d'eau initiale (L)")),
                ('quantite_eau_reste', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Quantité d'eau restante (L)")),
                ('heure_assoiffement_debut', models.TimeField(verbose_name="Heure d'assoiffement — début")),
                ('heure_assoiffement_fin', models.TimeField(verbose_name="Heure d'assoiffement — fin")),
                ('heure_abreuvement_debut', models.TimeField(verbose_name="Heure d'abreuvement — début")),
                ('heure_abreuvement_fin', models.TimeField(verbose_name="Heure d'abreuvement — fin")),
                ('date_validite_vaccin', models.DateField(verbose_name='Date de validité du vaccin')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_vaccination_eau', to='rapports.exploitation')),
            ],
            options={
                'verbose_name': 'Fiche vaccination — eau de boisson',
                'verbose_name_plural': 'Fiches vaccination — eau de boisson',
                'ordering': ['-date', '-numero_fiche'],
            },
        ),
        migrations.CreateModel(
            name='FicheVaccinationInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fiche', models.PositiveIntegerField(verbose_name='N° de la fiche')),
                ('date', models.DateField(verbose_name='Date')),
                ('age_sujets', models.CharField(max_length=50, verbose_name='Âge des sujets')),
                ('nombre_sujets', models.PositiveIntegerField(verbose_name='Nombre de sujets')),
                ('nombre_doses_utilise', models.PositiveIntegerField(verbose_name='Nombre de doses utilisées')),
                ('quantite_eau', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Quantité d'eau (L)")),
                ('type_eau_utilisee', models.CharField(blank=True, choices=[('PUITS', 'Puits'), ('FORAGE', 'Forage')], max_length=10, verbose_name="Type d'eau utilisée")),
                ('produit_complementaire', models.CharField(blank=True, max_length=150, verbose_name='Produit complémentaire utilisé')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début (injection)')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin (injection)')),
                ('date_validite_vaccin', models.DateField(verbose_name='Date de validité du vaccin')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_vaccination_injection', to='rapports.exploitation')),
            ],
            options={
                'verbose_name': 'Fiche vaccination — injection',
                'verbose_name_plural': 'Fiches vaccination — injection',
                'ordering': ['-date', '-numero_fiche'],
            },
        ),
        migrations.CreateModel(
            name='PoidsHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_numero', models.PositiveIntegerField(verbose_name='Semaine n°')),
                ('date', models.DateField(verbose_name='Date')),
                ('aliment_utilise', models.CharField(max_length=150, verbose_name="Aliment utilisé pour l'alimentation")),
                ('poids_moyen_vise', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Poids moyen hebdomadaire visé (g)')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semaines_poids', to='rapports.exploitation')),
            ],
            options={
                'verbose_name': 'Semaine de pesée',
                'verbose_name_plural': 'Semaines de pesée',
                'ordering': ['exploitation', 'semaine_numero'],
                'unique_together': {('exploitation', 'semaine_numero')},
            },
        ),
        migrations.CreateModel(
            name='PeseeQuotidienneOeufs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_pesee', models.TimeField(default='17:00', verbose_name='Heure de pesée')),
                ('nombre_oeufs_peses', models.PositiveIntegerField(verbose_name="Nombre d'œufs pesés (échantillon)")),
                ('poids_total_grammes', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Poids total (g)')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesees_oeufs', to='rapports.exploitation')),
            ],
            options={
                'verbose_name': 'Pesée quotidienne des œufs',
                'verbose_name_plural': 'Pesées quotidiennes des œufs',
                'ordering': ['-date'],
                'unique_together': {('exploitation', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PeseeIndividuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sujet', models.PositiveIntegerField(verbose_name='N° du sujet pesé')),
                ('poids_grammes', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Poids (g)')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesees', to='rapports.poidshebdomadaire')),
            ],
            options={
                'verbose_name': 'Pesée individuelle',
                'verbose_name_plural': 'Pesées individuelles',
                'ordering': ['numero_sujet'],
                'unique_together': {('semaine', 'numero_sujet')},
            },
        ),
    ]
