# Generated by Django 5.1.15 on 2026-09-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichevaccinationinjection',
            name='quantite_eau',
        ),
        migrations.RemoveField(
            model_name='fichevaccinationinjection',
            name='type_eau_utilisee',
        ),
        migrations.AddField(
            model_name='fichevaccinationeauboisson',
            name='image_etiquette',
            field=models.ImageField(blank=True, null=True, upload_to='etiquettes_vaccin_eau/', verbose_name='Image étiquette du vaccin'),
        ),
        migrations.AddField(
            model_name='fichevaccinationinjection',
            name='image_etiquette',
            field=models.ImageField(blank=True, null=True, upload_to='etiquettes_vaccin_injection/', verbose_name='Image étiquette du vaccin'),
        ),
        migrations.AddField(
            model_name='fichevaccinationinjection',
            name='nom_vaccin',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du vaccin'),
        ),
        migrations.AddField(
            model_name='fichevaccinationinjection',
            name='quantite_produit_ml',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Quantité du produit (ml)'),
        ),
        migrations.AddField(
            model_name='poidshebdomadaire',
            name='fourchette_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Fourchette de poids — maximum (g)'),
        ),
        migrations.AddField(
            model_name='poidshebdomadaire',
            name='fourchette_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Fourchette de poids — minimum (g)'),
        ),
    ]
