# Generated by Django 5.1.15 on 2026-09-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichevaccinationeauboisson',
            name='nombre_sujets',
        ),
        migrations.RemoveField(
            model_name='fichevaccinationinjection',
            name='image_etiquette',
        ),
        migrations.RemoveField(
            model_name='fichevaccinationinjection',
            name='nombre_sujets',
        ),
        migrations.CreateModel(
            name='ImageEtiquetteVaccinInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='etiquettes_vaccin_injection/', verbose_name='Image étiquette du vaccin')),
                ('televerse_le', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_etiquettes', to='rapports.fichevaccinationinjection')),
            ],
            options={
                'verbose_name': 'Image étiquette (injection)',
                'verbose_name_plural': 'Images étiquettes (injection)',
                'ordering': ['televerse_le'],
            },
        ),
    ]
