# Generated by Django 5.1.15 on 2026-09-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapports', '0002_remove_fichevaccinationeauboisson_nombre_sujets_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poidshebdomadaire',
            options={'ordering': ['exploitation', 'date'], 'verbose_name': 'Semaine de pesée', 'verbose_name_plural': 'Semaines de pesée'},
        ),
        migrations.AlterUniqueTogether(
            name='poidshebdomadaire',
            unique_together={('exploitation', 'date')},
        ),
        migrations.RemoveField(
            model_name='poidshebdomadaire',
            name='semaine_numero',
        ),
    ]
